### ISSUE TITLE
Multi-word links?

### ISSUE THREAD

**Issue by madranet** [ratfactor/vviki#2]
Is it possible tp create a link which is more than a single word?  

I'm adapting my existing VimWiki to VViki but I've got tons of links which are multiple words, so it'll be a major pain having to rename all the links and the files they point to.

**Comment by ratfactor** [comment]
I see that you've closed the issue. Did you find a satisfactory solution?

**Comment by madranet** [comment]
I couldn't get it to work at all ie.  nothing happened when I hit <enter> on even single words, so the question of multi-word links became a bit moot.

**Comment by ratfactor** [comment]
@madranet Well, that's no good. Sorry to hear it. :-(

I can only guess as to what might have gone wrong, but if you want to give it another shot, the first thing I'd check would be that the path and file extension settings are set correctly so that VViki can correctly detect your wiki pages. Example:

```
let g:vviki_root = "~/wiki"
let g:vviki_ext  = ".adoc"
```

To rule out a key binding conflict with the Enter key, you can also try calling the link-making functionality directly (which will also work on non-wiki pages, further helping pinpoint the problem). Put your cursor on a word in your document and then invoke:

```
:call VVEnter()
```

If that still doesn't work, the plugin may not be loaded at all.  You can also check with:

```
:echo g:loaded_vviki
```

Which should return 

```
1
```

on the command/status line.

**Comment by madranet** [comment]
I don't know if I'm "holding it wrong" or what, but I'm still having no joy. 

Here is my `~/.vimrc`

```
"VViki --the ascidoc wan
let g:vviki_root = "~/Jottacloud/vviki"
let g:vviki_ext  = ".adoc"
nnoremap <leader>ww :e ~/Jottacloud/vviki/index.adoc<cr> 
```

My wiki opens from the `<leader>ww` invocation and `:echo g:loaded_vviki` returns `1` as expected. But hitting `<RETURN>` when on a word does nothing at all.

If I put the cursor over a word [for example 'test']and use `:call VVEnter()` the text changes from `test` to `link:test[test]` but still doesn't function as a link. 

Does Vviki add any hidden text into the files or anything that I might be missing?  I've just converted an existing VimWiki to Vviki by changing the file extensions from `.md` to `.adoc` and was planning to go through and tidy up the syntax where AsciiDoc differs from MarkDown. 

 I can't see how that would effect anything. AsciiDoc and MarkDown are both plain-text, but just throwing that into the mix, in case there's some weirdness going on behind the scenes I'm not aware of.

**Comment by madranet** [comment]
UPDATE:

OK. I've just created a completely new Vviki to see if there was something in my existing one that Vviki didn't like and things are now working as expected. I can create links with the `<ENTER>` key.

Now to do some digging and find out why Vviki doesn't like my old ex-markdown files.

I'm still a bit puzzled though. My links are still showing like `link:test[test] `.  Is this expected? I thought Vviki would hide the link syntax as VimWiki does and just show the clickable word.

**Comment by ratfactor** [comment]
@madranet First off, I'm glad to hear a fresh wiki is (mostly) working.  If you can figure out what the difference is, I'd love to know.

And yes, nothing but plaintext is expected. No magic. I converted my own wiki from VimWiki's custom ".wiki" format to AsciiDoc ".adoc".  In fact, some of my old pages still have the original VimWiki syntax. :sweat_smile: 

As for the `link:test[test]` links not having the syntax concealed - you're absolutely right. It should work just like VimWiki.  So something is still amiss.  You can turn that feature explicitly _off_ by setting `let g:vviki_conceal_links = 0`, but it is on by default.

I'd be interested to know if you get the expected results for this:

1. Put your cursor over the `mylink` in `link:mylink[foo]`
2. Enter `:echo synIDattr(synID(line("."),col("."),1),"name")`
3. Then the same for `foo` in `link:mylink[foo]`

You should get `vvikiLinkGuts` for mylink first and `vvikiLink` for foo.

Here's how the syntax of a link is identified by VViki:

```
       vvikiLink
           |
    ---------------
    |             |

    link:test[test]
    ^^^^^^^^^^    ^        
        |         |
        -----------
             |
       vvikiLinkGuts
```

The `vvikiLinkGuts` portion is what should be concealed by Vim.

As an aside: VViki is intended to be more-or-less a drop-in replacement for VimWiki, so if it turns out that I need to improve the documentation or the plugin to make it easier to use/configure, please don't hesitate to make a suggestion. Thanks!

**Comment by madranet** [comment]
Well, this is very bizarre! 

I was just in the middle of a very long involved post here, showing how I was trying to convert from VimWiki to Vviki and where it was falling over... 

..and suddenly everything started working properly. I don't know what voodoo lay behind it but; at first my links were displayed by Vviki as `link:some text[some text]` although still functional.  I clicked on one and Vviki went to the linked page and, when I hit my back button to return to the index, the links were now displayed correctly with the extra AsciiDoc link syntax hidden. It's almost like [in browser terms] the index page needed refreshed in order to display properly.

I'm also pleased to note that my existing multi-word links are functioning correctly too, although it doesn't seem possible to create multi-word links from within Vviki [which was going to be my original question, all those aeons ago!]

By the way. For anyone else stumbling across this and who's trying to convert an existing VimWiki to Vviki format _[I'd imagine a lot of people trying Vviki will have an existing VimWiki they want to bring with them]_ here is the magic RegEx incantation you'll need to run across your existing VimWiki project files to convert all your existing links to VViki's AsciiDoc format:

```
Find:  (\[\[)(.*?)(\]\])

Replace: link:$2[$2]
```
Don't forget to change all your file extensions from `.md` to `.adoc` too!

Interesting postscript: As I found out when examining my existing VimWiki files while trying to troubleshoot this, VimWiki doesn't write links in its `.md` files in actual MarkDown syntax: `[Some Text](Some Text)` but instead uses wiki syntax `[[Some Text]]` even when set to use MarkDown as the wiki file format. 

>As an aside: VViki is intended to be more-or-less a drop-in replacement for VimWiki, so if it turns out that I need to improve the documentation or the plugin to make it easier to use/configure, please don't hesitate to make a suggestion. Thanks!

As I alluded to above, I'd imagine the vast majority of your potential users will be wanting to migrate an existing VimWiki.  Maybe include a quick mention of the process involved. Basically it just amounts to changing the file extensions and then running that RegEx I showed, but it might be useful to include that info, rather than leaving people to work it out themselves.

**Comment by ratfactor** [comment]
@madranet Glad to hear it all started working!

I think documenting the conversion of content from VimWiki .wiki/.md to AsciiDoc format is a great idea.  I'll see about creating a sample script to automate/semi-automate the conversion.  I'll create an issue here on GitHub to do that so I don't forget.

As for multi-word links, I suppose it would make sense to check for a visual selection when you press ENTER...except it would override the default ENTER action in visual mode. I'll have to think about that.

**Comment by madranet** [comment]
>As for multi-word links, I suppose it would make sense to check for a visual selection when you press ENTER..

I may be wrong. It's been quite a while since I fired up VimWiki and I've now uninstalled it to avoid conflict with Vviki, but I'm pretty sure this was how it was done there. 

>...except it would override the default ENTER action in visual mode. I'll have to think about that.

Is there a default `<ENTER>` action with selected text?  

~~It doesn't seem to do anything at all when I try it, apart from move the cursor to the next line.~~

Duh! --scratch that. Of course, it would first extend the selection to the end of the current line and then move the cursor down to the next line.  I'd not considered this as I'd been testing on pairs of words on a line by themselves.  

Hmmm... I Wonder how VimWiki did it then? I'm pretty sure I could just make arbitrary selections of words within a block of text and hit `<RETURN>` to make them into a link. Maybe I'm mis-remembering.

**Comment by ratfactor** [comment]
@madranet I finally tested the creation of multi-word links in VimWiki (since I use it at work).  Indeed, you create a visual selection and then hit ENTER.

I'm completely open to having link creation from a visual selection be added to VViki.  Since you use multi-word links, is that something you'd be interested in working on?

**Comment by madranet** [comment]
It's something I'd be interested in seeing in VViki. But it's not something I'm qualified to work on. I've no knowledge of VimScript, I'm afraid.

**Comment by ratfactor** [comment]
@madranet No problem, thanks for the answer. I think it would be very reasonable to add this ability to VViki.  I'm going to re-open this issue.

**Comment by ratfactor** [comment]
@madranet If you're still interested, I've added the multi-word link ability. It uses visual selections as we discussed.

From the help documentation for release v1.1.0:

```
g:vviki_visual_link_creation                      *vviki_visual_link_creation*

This setting allows you to select multiple words of text using Vim's visual
mode and turn them into a link by pressing the Enter key. The resulting link
page and description will both be the exact text selected visually.

This option is off by default. Turn it on like so:
>
    let g:vviki_visual_link_creation = 1
<
```
